
CREATE TABLE message (
    MessageID INT AUTO_INCREMENT PRIMARY KEY,
    SenderID INT NOT NULL,
    ReceiverID INT NOT NULL,
    Content TEXT NOT NULL,
    Time_stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SenderID) REFERENCES users (UserID) ON DELETE CASCADE,
    FOREIGN KEY (ReceiverID) REFERENCES users (UserID) ON DELETE CASCADE
);