
CREATE TABLE likes (
    LikeID INT AUTO_INCREMENT PRIMARY KEY,
    PostID INT NOT NULL,
    LikedBy INT NOT NULL,
    LikedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(PostID, LikedBy), 
    FOREIGN KEY (PostID) REFERENCES posts(PostID) ON DELETE CASCADE,
    FOREIGN KEY (LikedBy) REFERENCES users(UserID) ON DELETE CASCADE
);

select * from likes;