
CREATE TABLE resources (
    ResourceID INT AUTO_INCREMENT PRIMARY KEY,
    GroupID INT NOT NULL,
    UploadedBy INT NOT NULL,
    ResourceType VARCHAR(50),
    ResourceURL VARCHAR(255),
    UploadDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (GroupID) REFERENCES STUDY_GROUP(GroupID) ON DELETE CASCADE,
    FOREIGN KEY (UploadedBy) REFERENCES users (UserID) ON DELETE CASCADE
);